name: Deploy Application

on:
  push:
    branch: [ "deploy" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, xml, ctype, iconv, mysql, zip, curl
          tools: composer:v2

      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '26'

      - name: Install Node Dependencies & Build Assets
        run: |
          npm ci
          npm run build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PROD_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # --- DebugG
      - name: Debug SSH Agent & Forwarding
        run: |
          echo "=== 1. Sprawdzenie odcisku klucza w GitHub Actions ==="
          ssh-add -l

          echo "=== 2. Test czystego Forwardingu przez kontener do GitHuba ==="
          ssh -A -o StrictHostKeyChecking=accept-new -p 22678 deployer@get.ip.modus.ovh "ssh -T git@github.com" || true
      # --------------------------------

      - name: Install Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist --optimize-autoloader

      - name: Run Deployer
        run: vendor/bin/dep deploy -v
